---
apiVersion: v1
kind: Namespace
metadata: 
  name: brahmaiah

---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
  namespace: brahmaiah
spec:
  containers:
    - name: javawebappcontainer
      image: ashokit/javawebapp
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: javawebappsvc
  namespace: brahmaiah
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
...